### ISSUE TITLE
Is that possible to add my own view to arachne?

### ISSUE THREAD

**Issue by ghostku** [kirankoduru/arachne#16]
I make a small project with Arachne that parses some data and add it to SQLite. And I want to make some webpage with some info based on crapped data. Should I create a separate flask app or I can add a view function to arachne somehow?

**Comment by kirankoduru** [comment]
@ghostku I think this would be a great extension to add to __arachne__. Though at the moment I would believe that you manage the reads from as DB from a different flask app. I will add this to the roadmap for a future release.
