### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by ghowkay** [kirankoduru/arachne#7]
Hi, nice framework by the way..i have got it setup. when i run the application and go to the url on localhost to list the endpoints, it works, but when i try visiting an individual endpoint say http://localhost:5000/spiders/konga, it throws a 404 not found error

**Comment by kirankoduru** [comment]
hi @ghowkay, thank you for your appreciation. The url [http://localhost:5000/spiders/](http://localhost:5000/spiders/) will return a list of spiders. To run a spider you have to call the endpoint [http://localhost:5000/run-spider/kongo](http://localhost:5000/run-spider/kongo).

In my next release I will make the endpoints more evident. I understand it is confusing.

**Comment by kirankoduru** [comment]
Also @ghowkay , you can look at the [quickstart guide](http://arachne.readthedocs.org/en/latest/quickstart.html#quickstart) for more information.

**Comment by ghowkay** [comment]
Wow thanks for the quick response. No problem .ill give it a try. Cheers

**Comment by kirankoduru** [comment]
@ghowkay no problem. I will close this issue then.

**Comment by ghowkay** [comment]
uh oh. my apologies just started getting this error when i run python app.py

   from scrapy.log import ScrapyFileLogObserver
ImportError: cannot import name ScrapyFileLogObserver

Sorry to bother

**Comment by kirankoduru** [comment]
@ghowkay this is related to the version of Scrapy you might have installed. Are you sure you have Scrapy v0.24?

**Comment by ghowkay** [comment]
no i have the version 1. is there anyway i can replace the
scrapyfilelogobserver with another function. im using xmlspiders and
sitempap spiders which are unavailable in 0.24 i think

**Comment by kirankoduru** [comment]
@ghowkay sorry but I still have to update this project to support v1.0 of scrapy. I have that in the roadmap for a future release. Refer #4

**Comment by kirankoduru** [comment]
@ghowkay I have updated the project to be compatible with `Scrapy 1.0+` today. Please update your installation for `Arachne`.
