### ISSUE TITLE
pip install Arachne installs older version

### ISSUE THREAD

**Issue by talhashraf** [kirankoduru/arachne#9]
I noticed that whenever I install Arachne using `pip install Arachne` it installs `Arachne==0.3.1`. However, when I install it using `pip install git+ssh://git@github.com/kirankoduru/arachne.git` it installs `Arachne==0.4.0`.

`Arachne==0.3.1` isn't working for me. But `Arachne==0.4.0` works just fine.

**Comment by kirankoduru** [comment]
Hi @talhashraf. Version 0.4.0 is a work in progress. But if you would like to take a look at the diff heres a [link](https://github.com/kirankoduru/arachne/compare/v0.3.1...master)

**Comment by kirankoduru** [comment]
@talhashraf I have updated the project. Please re-install `Arachne`. It is now compatible with `Scrapy v1.0+`

**Comment by talhashraf** [comment]
@kirankoduru Nice. I will update our openstates project.
